#########################        BRITS CONFIG        ##########################

#### Dataset params ###########################################################
#dataset_name: [la_point, bay_point, la_bock, bay_bock, air, air36]
val_len: 0.1
adj_threshold: 0.1
window: 24  
stride: 1

#### Training params ##########################################################
whiten_prob: 0.05
scale_target: True

epochs: 200
patience: 20
loss_fn: l1_loss
lr_scheduler: cosine
lr: 0.001
batch_size: 32
batches_epoch: 160

#### Model params #############################################################
model_name: 'brits'
hidden_size: 64  
